### ISSUE TITLE
Switch the generated app from classic to modular Sinatra app

### ISSUE THREAD

**Issue by mattetti** [mattetti/wd-sinatra#26] opened 2013-03-25 22:24 UTC
As per #22, it would be better to switch to a modular style app. PR appreciated.

**Comment by kamui** [comment] 2013-05-10 05:56
There's a problem with the [test_helpers](https://github.com/mattetti/wd-sinatra/blob/master/lib/wd_sinatra/test_helpers.rb#L17):

``` ruby
class Requester
  include ::Rack::Test::Methods

  def app
    Sinatra::Application
  end
end
```

It defines an app method to return `Sinatra::Application` for `Rack::Test`, but here we actually need our named app name to work in the modular style. We could reopen `Requester` in the template test_helper, but I'm wondering why you don't just reopen `MiniTest::Unit::TestCase` and just include `Rack::Test` and other methods defined in `TestApi` as helper methods you can include as well?

``` ruby
class MiniTest::Unit::TestCase
  include Rack::Test::Methods
  include WDSinatra::Test::Methods

  def app
    YourAppName.new
  end
end
```

Then we wouldn't need to scope everything with `TestApi`, we could call `header()` in our tests without having to pass a hash into TestApi.get. I think I would prefer direct access to `Rack::Test` methods, and pick and choose with helper methods I want/need.

**Comment by mattetti** [comment] 2013-05-10 08:41
@kamui seems fine, I think the only reason why I didn't do that was because I didn't have a way to know `YourAppName`

**Comment by kamui** [comment] 2013-05-10 22:35
I'll put the TestApi changes in a different PR and close this since it's now a dupe of #29.

**Closed as completed by kamui** 2013-05-10 22:35 UTC
Labels: duplicate
